name: Checks

# Specifi The Trigger
on:
    pull_request:
        branches: [main]

jobs:
    test_lint:
        name: Test and Lint
        uses: ./.github/workflows/test-and-lint.yml # Script that we want to run
        secrets:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER}}
            DOCKERHUB_TOKEN: ${{ secretS.DOCKERHUB_TOKEN }}